/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo;

public class App {
    public String getGreeting() {
        return "Welcome to our demo today - KinIHon team :)!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
